#!/bin/sh

if [ "$1" != "configure" ]; then
  exit 1
fi

if [ -x "/etc/init.d/remote_syslog" ]; then
  update-rc.d remote_syslog defaults >/dev/null
 
  if [ -n "$2" ]; then
    # Upgrade
    invoke-rc.d remote_syslog restart
  fi
fi

